bpscmanager/config/routes.rb
Bpscmanager::Application.routes.draw do

  resources :collections

  root :to => 'home#index'

end

bpscmanager/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

bpscmanager/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= begin
	    extname = File.extname(filename).gsub(/^\./, '')
      "/javascripts/ckeditor/filebrowser/images/thumbs/#{extname}.gif"
	  end
	end
end

bpscmanager/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

bpscmanager/app/models/collection.rb
class Collection < ActiveRecord::Base
    validates :title, :presence => true
    validates :description, :presence => true
    validates :collectiontype, :presence => true
    validates :description, :length => { :maximum => 110 }
    has_attached_file :listimage
end

bpscmanager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

bpscmanager/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new
    @collections = Collection.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, :notice => 'Collection was successfully created.' }
        format.json { render :json => @collection, :status => :created, :location => @collection }
      else
        format.html { render :action => "new" }
        format.json { render :json => @collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, :notice => 'Collection was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :ok }
    end
  end
end

bpscmanager/app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout "home"
  def index
    @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @collections }
    end
  end
end

bpscmanager/app/helpers/application_helper.rb
module ApplicationHelper
end

bpscmanager/app/helpers/collections_helper.rb
module CollectionsHelper
end

bpscmanager/app/helpers/home_helper.rb
module HomeHelper
end

bpscmanager/app/views/collections/_form.html.erb
<%= semantic_form_for(@collection) do |form| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 	<%= form.input :title, :label => "Collection Title" %>
 	<%= form.input :shortname %>
	<%= form.input :description, :input_html => { :size => '80px'} %>
	<%= form.input :essay, :html_options => { :class => 'tiny_mce' } %> 

	<script type="text/javascript">
	  tinyMCE.init({
	   mode : "textareas",
	    theme : "advanced",
	    theme_advanced_buttons1 : "mybutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink",
	    theme_advanced_buttons2 : "",
	    theme_advanced_buttons3 : "",
	    theme_advanced_toolbar_location : "top",
	    theme_advanced_toolbar_align : "left"
	  });
	</script>
	<%= form.input :collectiontype, :label => "Type of Collection", :as => :check_boxes, :include_blank => false, :collection => [["Major Holding", "major"], ["Web Exhibit", "web"], ["Current Exhibit", "new"], ["Past Exhibit", "past"]] %>
	<%= form.input :subject, :label => "Subjects", :as => :select, :include_blank => false %>
	<%= form.input :startyear, :label => "Start Year" %>
	<%= form.input :acquisitionyear, :label => "Acquisition Year" %>
	<%= form.input :listimagesize, :label => "List image size", :as => :select, :include_blank => false, :collection => ["default", "wide", "long", "biggest"] %>
	<%= form.input :listimage, :label => "Card Image", :as => :file %>
    <%= form.buttons %>
<% end %>

bpscmanager/app/views/collections/edit.html.erb
	<div id="main">
<h1>Edit <%= @collection.title %> </h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>
</div>

bpscmanager/app/views/collections/index.html.erb
<table class="manage-list">
	<tr>
		<th>list image</th>
		<th>title</th>
		<th>Start Year</th>
		<th>Acquisition Year</th>
		<th>Description</th>  
		<th>Actions</th>
	</tr>

<% @collections.each do |collection| %>
<tr>
	<td><%= image_tag collection.listimage.url %></td>
	<td><%= link_to collection.title, collection %></td>
	<td><%= collection.startyear %></td>
	<td><%= collection.acquisitionyear %></td>
	<td><%= collection.description %></td>  
	<td><%= link_to 'Edit', edit_collection_path(collection) %>
	<%= link_to 'Delete', @collection, :confirm => 'Are you sure?', :method => :delete %></td>
	 
</tr>
 
<% end %>
</table>

bpscmanager/app/views/collections/new.html.erb
	<div id="main" class="add">
<h1>Add a new collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>
</div>

bpscmanager/app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @collection.title %>
</p>

<p>
  <b>Short Name:</b>
  <%= @collection.shortname %>
</p>

<p>
  <b>Description:</b>
  <%= @collection.description %>
</p>

<p>
  <b>Essay:</b>
  <%=raw @collection.essay %>
</p>

<p>
  <b>Subject:</b>
  <%= @collection.subject %>
</p>

<p>
  <b>Collection Type:</b>
  <%= @collection.collectiontype %>
</p>

<p>
  <b>Start Year:</b>
  <%= @collection.startyear %>
</p>

<p>
  <b>Acquisition Year:</b>
  <%= @collection.acquisitionyear %>
</p>
<%= image_tag @collection.listimage.url %>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Destroy', @collection, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', collections_path %>

bpscmanager/app/views/home/index.html.erb
<section id="content">
		<h2 class="filters" id="sort-by">Our Collections - <span class="filter-title">All Collections and Exhibits</span>
				<p>sort by: <a href="#">importance</a> | <a href="#name">name</a> | <a href="#sdate">start date</a></p></h2>
	<section id="options">

	   

    <ul id="filters">
		<li><h2>type</h2></li>
      <li><a href="#collections" data-filter="*">show all</a></li>
		<li><a href="#major" data-filter=".major">major holdings</a></li>
      <li><a href="#web" data-filter=".web">web exhibits</a></li>
		<li><a href="#new" data-filter=".new">new and current exhibits</a></li>
		<li><a href="#past" data-filter=".past">past exhibits</a></li>
    </ul>

	<ul id="filters">
		<li><h2>subject</h2></li>
		 <li><a href="#book" data-filter=".book">the history of the book</a></li> 
		 <li><a href="#press" data-filter=".press">small presses</a></li> 
		<li><a href="#artbooks" data-filter=".artbooks">art books</a></li> 
		<li><a href="#british" data-filter=".british">british literature</a></li> 
		<li><a href="#children" data-filter=".children">children's literature</a></li> 
		<li><a href="#ana" data-filter=".ana">canadiana and americana</a></li>
	</ul>

</section>

<ul id="container">

<% @collections.each do |collection| %>
<li class="cols <%= collection.collectiontype %> <%= collection.subject %> <%= collection.listimagesize %>">
	<%= image_tag collection.listimage.url %>
	<h2 class="name"><%= link_to collection.title, collection %></h2>
	<p class="sdate"><%= collection.startyear %></p>
	<p class="adate"><%= collection.acquisitionyear %></p>
		<div class="details">
			<p><%= collection.description %></p>  
		</div>
</li>
 
<% end %>
</ul>
<script>
  $(function(){
	
		var $container = $('#container');
		
		var f=document.URL.split('#')[1];
		if (f!=undefined){
			var selector="."+f;
			if (selector==".web"){
				var ft="Web Exhibits";
			}
			else if (selector==".major"){
				var ft="Major Holdings";
			}
			else if (selector==".other"){
				var ft="Other Collections";
			}
			else if (selector==".new"){
				var ft="New and Current Exhibits";
			}
			$('.filter-title').text(ft);
		}
		else{
			var selector='*';
		}
		$container.isotope({ 
			filter: selector,
			 masonry : {
			    columnWidth :1
			  },
			getSortData : {
			    name : function ( $elem ) {
			      return $elem.find('.name').text();
			    },
			    sdate : function ( $elem ) {
			      return $elem.find('.sdate').text();
			    }
			  }
		});

		
		$('#sort-by a').click(function(){
			var sortName = $(this).attr('href').slice(1);
		 	$container.isotope({ sortBy : sortName });
			return false;
		});
		
		$('#filters a').click(function(){
	  		var selector = $(this).attr('data-filter');
	  		$container.isotope({ filter: selector });
			if (selector==".web"){
				var ft="Web Exhibits";
			}
			else if (selector==".major"){
				var ft="Major Holdings";
			}
			else if (selector==".other"){
				var ft="Other Collections";
			}
			else if (selector==".new"){
				var ft="New and Current Exhibits";
			}
			else if (selector==".past"){
				var ft="Past Exhibits";
			}
			else if (selector==".book"){
				var ft="The History of the Book";
			}
			else if (selector==".press"){
				var ft="Small Presses";
			}
			else if (selector==".artbooks"){
				var ft="Art Books";
			}
			else if (selector==".children"){
				var ft="Children's Literature";
			}
			else if (selector==".british"){
				var ft="British Literature";
			}
			else if (selector==".ana"){
				var ft="Canadiana and Americana";
			}
			else{
				var ft="All Collections and Exhibits";
			}
		 	$('.filter-title').text(ft);
	  		return false;
		});	
		$('.collection').hoverIntent(fin,fout);
		function fin(){  
			$(this).find('img').delay(100).fadeTo(200, 0.1);
			$(this).find('h2').addClass('triggered');
			$(this).find('.details').delay(100).fadeIn(200);
		}
		function fout(){ 
			var h = $(this).height();
			var h2 = $(this).height()-47;
			$(this).find('.details').fadeOut(300);
			$(this).find('img').fadeTo(300, 1);
			$(this).find('h2').removeClass('triggered');
		}
		$(".collection").click(function(){
		     window.location=$(this).find("a").attr("href");
		     return false;
		});
  });
</script>

bpscmanager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bruce Peel Special Collections - editing tool</title>
  <%= stylesheet_link_tag    "application" %>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Judson' rel='stylesheet' type='text/css'>

</head>
<body>
	<div id="header" class="col">
		<a href="http://uofa-libraries.github.com/brucepeel"><%= image_tag "logosm.png", :alt=> "University of Alberta Libraries Logo" %></a>
		<ul class="nav-int">
	
			<li><%= link_to 'Add a Collection', new_collection_path %></li>
			<li><%= link_to 'Manage Collections', collections_path %></li>
			<li><%= link_to 'View Collections', root_path %></li>
		</ul>
	</div>


<%= yield %>


</body>
</html>

bpscmanager/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bruce Peel Special Collections</title>
  <%= stylesheet_link_tag    "application" %>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Judson' rel='stylesheet' type='text/css'>

</head>
<body>
	<div id="header" class="col">
		<a href="http://uofa-libraries.github.com/brucepeel"><%= image_tag "logosm.png", :alt=> "University of Alberta Libraries Logo" %></a>
		<ul class="nav-int">
			<li><a href="hours.html">Hours and Location</a></li>
			<li><a href="about.html">About the Library</a></li>
			<li><a href="contact.html">Contact Us</a></li>
			<li><a href="terms.html">Policies and Terms of Use</a></li>		
			<li><a href="links.html">Relevant Links</a></li>
		</ul>
	</div>


<%= yield %>

<%= link_to 'manage collections', collections_path, :class => "manage" %>
</body>
</html>